# Scenario 1: Creazione di un Deployment Nginx

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: 
        ports:
        - containerPort: 80